template-repository: "tschm/.config-templates"
template-branch: "main"
include: |
    .devcontainer/
    .github/
    tests/
    .editorconfig
    .pre-commit-config.yaml
    CODE_OF_CONDUCT.md
    CONTRIBUTING.md
    LICENSE
    Makefile
    ruff.toml
